// <auto-generated />
using System;
using InteractHub_Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InteractHub_Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516045626_AddNewTables")]
    partial class AddNewTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.4.25258.110")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Comment", b =>
                {
                    b.Property<string>("IdComment")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IdPost")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentCommentId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdComment");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Comment_CreatedAt");

                    b.HasIndex("IdPost")
                        .HasDatabaseName("IX_Comment_IdPost");

                    b.HasIndex("IdTaiKhoan")
                        .HasDatabaseName("IX_Comment_IdTaiKhoan");

                    b.HasIndex("ParentCommentId")
                        .HasDatabaseName("IX_Comment_ParentCommentId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Friendship", b =>
                {
                    b.Property<string>("IdNguoiGui")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdNguoiNhan")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdNguoiGui", "IdNguoiNhan");

                    b.HasIndex("IdNguoiNhan")
                        .HasDatabaseName("IX_Friendship_IdNguoiNhan");

                    b.ToTable("Friendship", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Hashtag", b =>
                {
                    b.Property<string>("IdHashtag")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdHashtag");

                    b.HasIndex("NoiDung")
                        .IsUnique()
                        .HasDatabaseName("UX_Hashtag_NoiDung");

                    b.ToTable("Hashtag", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Like", b =>
                {
                    b.Property<string>("IdTaiKhoan")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdPost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdTaiKhoan", "IdPost");

                    b.HasIndex("IdPost")
                        .HasDatabaseName("IX_Like_IdPost");

                    b.ToTable("Like", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Notification", b =>
                {
                    b.Property<string>("IdNotification")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdPost")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("TriggeredByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdNotification");

                    b.HasIndex("IdPost")
                        .HasDatabaseName("IX_Notification_IdPost");

                    b.HasIndex("IdTaiKhoan")
                        .HasDatabaseName("IX_Notification_IdTaiKhoan");

                    b.HasIndex("TriggeredByUserId")
                        .HasDatabaseName("IX_Notification_TriggeredByUserId");

                    b.HasIndex("IdTaiKhoan", "IsRead")
                        .HasDatabaseName("IX_Notification_IdTaiKhoan_IsRead");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Post", b =>
                {
                    b.Property<string>("IdPost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("IdTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParentPostId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPost");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Post_CreatedAt");

                    b.HasIndex("IdTaiKhoan")
                        .HasDatabaseName("IX_Post_IdTaiKhoan");

                    b.HasIndex("ParentPostId")
                        .HasDatabaseName("IX_Post_ParentPostId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.PostHashtag", b =>
                {
                    b.Property<string>("IdPost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdHashtag")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPost", "IdHashtag");

                    b.HasIndex("IdHashtag")
                        .HasDatabaseName("IX_PostHashtag_IdHashtag");

                    b.ToTable("PostHashtag", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.PostMedia", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PostId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_PostMedia_PostId");

                    b.ToTable("PostMedia", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.PostReport", b =>
                {
                    b.Property<string>("IdReport")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdPost")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdReport");

                    b.HasIndex("IdPost")
                        .HasDatabaseName("IX_PostReport_IdPost");

                    b.HasIndex("IdTaiKhoan")
                        .HasDatabaseName("IX_PostReport_IdTaiKhoan");

                    b.ToTable("PostReport", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Story", b =>
                {
                    b.Property<string>("IdStory")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Caption")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(hour, 24, SYSUTCDATETIME())");

                    b.Property<string>("IdTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdStory");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Story_CreatedAt");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_Story_ExpiresAt");

                    b.HasIndex("IdTaiKhoan")
                        .HasDatabaseName("IX_Story_IdTaiKhoan");

                    b.ToTable("Story", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Comment", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany("Comments")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InteractHub_Shared.Data.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Friendship", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "NguoiGui")
                        .WithMany("SentFriendships")
                        .HasForeignKey("IdNguoiGui")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "NguoiNhan")
                        .WithMany("ReceivedFriendships")
                        .HasForeignKey("IdNguoiNhan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Like", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany("Likes")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Notification", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "Post")
                        .WithMany("Notifications")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany("Notifications")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TriggeredByUser")
                        .WithMany("TriggeredNotifications")
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Post");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TriggeredByUser");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Post", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany("Posts")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "ParentPost")
                        .WithMany("Reposts")
                        .HasForeignKey("ParentPostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPost");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.PostHashtag", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.Hashtag", "Hashtag")
                        .WithMany("PostHashtags")
                        .HasForeignKey("IdHashtag")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "Post")
                        .WithMany("PostHashtags")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hashtag");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.PostMedia", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "Post")
                        .WithMany("PostMedias")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.PostReport", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.Post", "Post")
                        .WithMany("PostReports")
                        .HasForeignKey("IdPost")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany("PostReports")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Post");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Story", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", "TaiKhoan")
                        .WithMany("Stories")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InteractHub_Shared.Data.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("PostReports");

                    b.Navigation("Posts");

                    b.Navigation("ReceivedFriendships");

                    b.Navigation("SentFriendships");

                    b.Navigation("Stories");

                    b.Navigation("TriggeredNotifications");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Hashtag", b =>
                {
                    b.Navigation("PostHashtags");
                });

            modelBuilder.Entity("InteractHub_Shared.Data.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");

                    b.Navigation("Notifications");

                    b.Navigation("PostHashtags");

                    b.Navigation("PostMedias");

                    b.Navigation("PostReports");

                    b.Navigation("Reposts");
                });
#pragma warning restore 612, 618
        }
    }
}
